### ISSUE TITLE
Code Dupluication

### ISSUE THREAD

**Issue by Manjindergit** [janaksk/Info4235Game#6]
So we've got some duplicate code we're writing in each level, we need to make a spearate file like levelDispalyFunctionality

-  the code inside init () could be separate function
- the scorereader in a level could be separate fucniton
- playing sound effect in update
- collect star method is almost same in all levels, just need to be passed on a variable for next Level

- Im not sure about this one, but maybe we should start loading assets at start in loading page, saw this in example game , have to research more to see how it would really play out
-

**Comment by janaksk** [comment]
Fixed
